notifications:
  email: false

sudo: false

language: node_js

node_js:
  - "14"

python:
  - "3.6"

services:
  - docker

before_script:
  - pip install --user -r docs/requirements.txt
  - npm install prettier

script:
  - ./run-tests.sh
