# This file is part of REANA.
# Copyright (C) 2020 CERN.
#
# REANA is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

name: CI

on: [push, pull_request]

jobs:
  lint-shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run shell script static analysis
        run: |
          sudo apt-get install shellcheck
          ./run-tests.sh --check-shellscript

  docs-sphinx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install system dependencies
        run: sudo apt-get update -y

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r docs/requirements.txt

      - name: Run Sphinx documentation with doctests
        run: ./run-tests.sh --check-sphinx

  format-prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Install project dependences
        run: npm install -g prettier

      - name: Run prettier code formatter
        run: ./run-tests.sh --check-prettier

  js-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Install project dependences
        run: npm install

      - name: Run javascript tests
        run: ./run-tests.sh --check-js-tests

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build docker image
        run: ./run-tests.sh --check-docker-build
